# Generated by Django 3.0.5 on 2023-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='hashId',
            field=models.TextField(default=0),
        ),
    ]
