# Generated by Django 3.0.5 on 2023-07-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_hashid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='hashId',
        ),
    ]
